language: node_js
node_js:
  - '14'
cache:
  yarn: true
  directories:
    - dist
    - .cache
script:
  - yarn build
env:
  - VUE_APP_RESUME_CONTENT_STRING: $RESUME_CONTENT

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master