name: Build and Deploy Application

on:
  push:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: yarn install
    
    - name: Build
      run: yarn build
    
    - name: DEBUG
      run: ls -la

    - name: Upload build artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

  validate-and-deploy:
    needs: build
    name: Validate and Deploy Terraform
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
      TF_CLOUD_HOSTNAME: "${{ secrets.TF_CLOUD_HOSTNAME }}"
      TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifacts

    - name: DEBUG
      run: ls -la

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
