name: Build and Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: yarn install
  
    - name: Copy Resume Contents
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: src/assets/resume.json
        json: ${{ vars.RESUME_JSON }}
    
    - name: Build
      run: yarn build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist

  validate-and-deploy:
    needs: build
    name: Validate and Deploy Terraform
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
      TF_CLOUD_HOSTNAME: "${{ secrets.TF_CLOUD_HOSTNAME }}"
      TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: terraform/dist

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
        terraform_version: 1.5.0

    - name: Set Terraform Workspace
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "TF_WORKSPACE=${{ secrets.TF_WORKSPACE_STAGING }}" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "TF_WORKSPACE=${{ secrets.TF_WORKSPACE_PROD }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Auto-format Terraform files
      if: github.event_name == 'pull_request'
      run: |
        terraform fmt -recursive
        if [ -n "$(git diff --exit-code "*/**.tf")" ]; then
          git config --global user.name "${{ vars.GIT_BOT_NAME }}"
          git config --global user.email "${{ vars.GIT_BOT_EMAIL }}"
          git commit -am "Auto-format Terraform files"
          git push origin HEAD:$GITHUB_REF
        fi
      shell: bash
      working-directory: terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
