name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (staging or prod)'
        required: true
        default: 'staging'
        options:
          - staging
          - prod

jobs:
  destroy:
    name: Destroy Terraform
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      TF_CLOUD_HOSTNAME: "${{ secrets.TF_CLOUD_HOSTNAME }}"
      TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
      TF_DATA_DIR: "terraform"
      TF_WORKSPACE_PROD: "${{ secrets.TF_WORKSPACE_PROD }}"
      TF_WORKSPACE_STAGING: "${{ secrets.TF_WORKSPACE_STAGING }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
          terraform_version: 1.5.0

      - name: Set Terraform Workspace
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo TF_WORKSPACE="${{ secrets.TF_WORKSPACE_STAGING }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo TF_WORKSPACE="${{ secrets.TF_WORKSPACE_PROD }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
